version: '3'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: root

  nginx:
    image: nginx:stable-alpine
    restart: always
    network_mode: "host"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/conf/nginx.conf:/etc/nginx/nginx.conf

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  db-data:
